Repository NRL-Plasma-Physics-Division/turbopy, pull requests merged in 2020-07, with the labels that each got.

#20 update docstring for Simulation class
  turbopy/core.py
Labels: documentation

#31 Update "CSVDiagnosticsOutput" Docstring
  turbopy/diagnostics.py
Labels: documentation

#51 More Issue Templates
  .github/ISSUE_TEMPLATE/DISCUSSION.md
  .github/ISSUE_TEMPLATE/DOCUMENTATION.md
  .github/ISSUE_TEMPLATE/QUESTION.md
  .github/ISSUE_TEMPLATE/TESTS.md
Labels: enhancement

#55 Add documentation to Grid class
  turbopy/core.py
Labels: documentation

#12 Create documentation for turboPy
  .gitignore
  .readthedocs.yml
  docs/api.rst
  docs/conf.py
  docs/getting_started.rst
  docs/index.rst
  docs/tutorials.rst
  environment.yml
  turbopy/__init__.py
  turbopy/core.py
  turbopy/diagnostics.py
Labels: documentation

#69 Adds documentation and tests for SimulationClock
  tests/test_core.py
  turbopy/core.py
Labels: documentation, tests

#60 Add tests for Grid class in core.py
  tests/test_core.py
Labels: tests

#72 Add documentation to FieldDiagnostic in diagnostics.py
  turbopy/diagnostics.py
Labels: documentation

#88 Add integration tests for block_on_spring
  tests/conftest.py
  tests/fixtures/block_on_spring/block_on_spring.py
  tests/fixtures/block_on_spring/output_backwardeuler/block_p.csv
  tests/fixtures/block_on_spring/output_backwardeuler/block_x.csv
  tests/fixtures/block_on_spring/output_backwardeuler/time.csv
  tests/fixtures/block_on_spring/output_forwardeuler/block_p.csv
  tests/fixtures/block_on_spring/output_forwardeuler/block_x.csv
  tests/fixtures/block_on_spring/output_forwardeuler/time.csv
  tests/fixtures/block_on_spring/output_leapfrog/block_p.csv
  tests/fixtures/block_on_spring/output_leapfrog/block_x.csv
  tests/fixtures/block_on_spring/output_leapfrog/time.csv
  tests/test_bos.py
  tests/test_pif.py
Labels: tests

#89 Add tests to simulation class methods
  tests/test_core.py
Labels: tests
